server:
  port: ${app.port}
spring:
  application:
    name: im-service-app
  profiles:
    active: dev

# eureka 基本信息配置
eureka:
  instance:
    # 指定ip
    ip-address: ${app.host}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.host}:${app.eureka.port}/eureka/