eureka:
  instance:
    # 注册到eureka ip地址
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
    # 因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: false
    # 因为自己是为注册中心，不需要检索服务
    fetch-registry: false
  # dev环境时关闭自我保护机制，保证不可用服务及时剔除
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000