server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: gateway-app
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
          lower-case-service-id: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）   简单尝试
        - id: app-user
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://user-web-app
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            ## 转发地址格式为 uri/archive
            - Path=/api/user/**
          filters:
            - StripPrefix=2
# eureka 基本信息配置
eureka:
  instance:
    ##指定ip
    ip-address: ${app.host}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.host}:${app.eureka.port}/eureka/